### ISSUE TITLE
visible 'tier list'

### ISSUE THREAD

**Issue by nuzcraft** [nuzcraft/row-jam-bow#10]
the player can swap from rock to paper to scissors, but they need to see this on screen some how.

Add a triangle of the 3 different types and indicate which the player currently is, and which they will switch to when they press the space bar.

thought: this _could_ be a triangle, but it could also just be some text that indicates the next switch. But, a triangle could also indicate which forms beat which

**Comment by felipebrunetti94** [comment]
Got it, where do you get your sprites ?I was thinking like, changing the character for a close fist for rock, open for paper and something for scisor kkk 
Any ideas  ?

**Comment by nuzcraft** [comment]
that is a good idea (I think I wrote something like that on #5). I've been drawing the sprites myself using Aseprite, but you could use any sort of art or photo editing software (GIMP is good).

**Comment by felipebrunetti94** [comment]
Okay, I though you got them in some repo, but it is okay, i can do the drawing right now, but I'll try some thing later today.

**Comment by nuzcraft** [comment]
I didn't really do this, but I did add and instruction screen with the basics (rock beats scissors etc)
