### ISSUE TITLE
increase number of levels

### ISSUE THREAD

**Issue by nuzcraft** [nuzcraft/row-jam-bow#11]
currently, once you beat level 6, the game will reset. Please update this so the max level is 8 or 10. 

This may end up being too hard (since so many monsters will spawn in), but worth a shot.

**Comment by felipebrunetti94** [comment]
Maybe, if you kill a plus monster a anti monster spawn after his death, with this we can make the level harder but still keep a limited number of monsters. 
What you think ?

And sorry about the sprites, I suck at drawing, but can help with the coding.

**Comment by nuzcraft** [comment]
That seems pretty cool to me. Ha, I’m not much of an artist either.
