### ISSUE TITLE
Spell Description

### ISSUE THREAD

**Issue by nuzcraft** [nuzcraft/row-jam-bow#15]
Add a popup box that shows up when you hover over a spell with a description.

**Comment by felipebrunetti94** [comment]
Nice to see you my Friend, I'll try this one

**Comment by felipebrunetti94** [comment]
I though about  a new feature. If you are out of spells you can trade one life point for a spell
Or if you already have a spell you can change half life to a new random spell.
What do you think ?

**Comment by felipebrunetti94** [comment]
Ohh by the way, i need the description of every spell we have.

**Comment by nuzcraft** [comment]
That sounds pretty awesome! 

I’ll make an issue for it.
