### ISSUE TITLE
Trading life for Spells

### ISSUE THREAD

**Issue by nuzcraft** [nuzcraft/row-jam-bow#17]
in #15, a suggestion from @felipebrunetti94 "If you are out of spells you can trade one life point for a spell. Or if you already have a spell you can change half life to a new random spell."

Spell slots are worth 3 gold (collecting 3 gold will get you a new slot and a new spell), So a life point might be too cheap. This is a cool feature though and should be implemented.

**Comment by felipebrunetti94** [comment]
hey @nuzcraft , which button key should this trading feature, be ?

**Comment by felipebrunetti94** [comment]
I made a first version of the feature, we need visual warning when the player have hp < 2. Any ideas ?

**Comment by nuzcraft** [comment]
there's an issue where new slots aren't kept when advancing to the next level. This needs to be fixed, then we can push for v0.3

**Comment by nuzcraft** [comment]
I'm going to change this so that its a straight swap, 3 life for a new spell slot
