### ISSUE TITLE
enemy progression

### ISSUE THREAD

**Issue by nuzcraft** [nuzcraft/row-jam-bow#3]
add a small system to allow harder enemies to only show up on later levels, and easier enemies to show up less

**Comment by felipebrunetti94** [comment]
Hey, i was doing a progression like this: 
first 3 levels only weak enemies
next levels up to 6, goes like this
4: 2 weak 2 normal
5: 1 weak 3 normal 1 strong
6: 3 normal 3 strong
6> : 1 weak 1 normal , fill with strong type monsters.
sound good ?

**Comment by nuzcraft** [comment]
That sounds good to me. I figured the easiest way will be to check the level, then add monsters to the monster list that’s used to add a new monster to the level. Is that what you were thinking?

Nuz

**Comment by felipebrunetti94** [comment]
Yeah, exactly...
Just one question, what were you thinking with the anti monster type, they should be in higher levels or is it okay, put them in weaker
 levels ?

**Comment by nuzcraft** [comment]
I think either way works. They currently aren’t any tougher, they are just
supposed to take and deal damage opposite of their type (not sure if it’s
working correctly though).

Nuz

**Comment by felipebrunetti94** [comment]
Well... i tried a level progression system, give it a try and give me some feedback. 
I was thinking, we could add a tutorial or a control guide, it took me some time to learn the commands...

**Comment by nuzcraft** [comment]
Thanks! I’ll take a look sometime today. I agree, a controls sheet would be helpful; the controls are only in the readme at the moment. I’ve also uploaded v0.2 to nuzcraft.itch.io/row-jam-brough.

Nuz

**Comment by felipebrunetti94** [comment]
Pretty cool, i like it.
