### ISSUE TITLE
cycle through rock, paper, scissors as player

### ISSUE THREAD

**Issue by nuzcraft** [nuzcraft/row-jam-bow#6]
the player can spend a turn to cycle to a different form

**Comment by felipebrunetti94** [comment]
hey can i help ?

**Comment by nuzcraft** [comment]
Yea, go for it! This is just a personal project, but feel free to poke at
it. Not sure what I need to do on GitHub to allow it though.

**Comment by felipebrunetti94** [comment]
I just need to fork it kkk tks
